### ISSUE TITLE
Homebrew package no available

### ISSUE THREAD

**Issue by SlippyJimmy** [quantonganh/snippets-ls#5]
`No available formula or cask with the name "quantonganh/tap/snippets-ls".`

**Comment by quantonganh** [comment]
Thank you for reporting this.

The reason is [I had just created another formulae](https://github.com/quantonganh/homebrew-tap/commit/71f4048d1e2218fd26b67641fbbe85877e1f3307) in the `Formula` subdirectory, that it caused this one (and all others placed in the repository's root) [to be ignored](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap):

> Tap formulae follow the same format as the core’s ones, and can be added under either the Formula subdirectory, the HomebrewFormula subdirectory or the repository’s root. The first available directory is used, other locations will be ignored.

It has been [fixed](https://github.com/quantonganh/snippets-ls/commit/5bb64842200517cbd93b09c709bc04e3d3a97d46), please try again.
